name: Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Docker
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet

#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Get .env from secrets
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

#      - name: Generate key
#        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Build Docker image
        run: docker build -t asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPO_NAME }}/example-app-app:${{ github.sha }} -f Dockerfile_ubuntu .

      - name: Push Docker image
        run: docker push asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPO_NAME }}/example-app-app:${{ github.sha }}

      - name: Deploy to GKE
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cat $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
          gcloud container clusters get-credentials cluster-1 --zone asia-east1-a --project smiling-stock-425106-c9
          sed -i 's|image: asia-east1-docker.pkg.dev/smiling-stock-425106-c9/devops-repo/example-app-app:latest|image: asia-east1-docker.pkg.dev/${GCP_PROJECT_ID}/${REPO_NAME}/example-app-app:${IMAGE_TAG}|' k8s/deployment.yaml
          cat k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: '#action'
          # For posting a simple plain text message
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
